baseURL = "https://mercedesporras.github.io/my_launchx_blog/"
languageCode = "en-us"
title = "Bitácora de Viaje de Lilia Mercedes Ambrosio Porras"
theme = "hugo-winston-theme"
relativeURLs = true
canonifyURLs = true

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
paginate = 3

[params]
  google_analytics_id = ""
  # Hey Explorer aquí pon tu IG 👇
  twitter_handle = "@mercedes.porras"
  showAuthorOnHomepage = true
  showAuthorOnPosts = false
  showPostsOnHomepage = false
  addFrame = true
  addDot = true
